
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/16/selfswin-60ep-Custom-16-ep=59.ckpt -tag "768 decoder ch" --cross_val 5
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/simclr/15/simclr-400ep-custom-supervised-15-ep=59.ckpt -tag "768 decoder ch" --cross_val 5 --arch_type "crag"
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/projects/mocov2plus-400ep-5-ep=114.ckpt -tag "768 decoder ch" --cross_val 5 --arch_type "crag"
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/projects/byol-400ep-8-ep=41.ckpt -tag "768 decoder ch" --cross_val 5 --arch_type "crag"
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -tag "768 decoder ch" --cross_val 5 --arch_type "crag"
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -tag "768 decoder ch" --cross_val 5 --arch_type "wss" --out 4
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_TransUnet.json -tag "768 decoder ch" --cross_val 5 --arch_type "crag" --n_epochs 150
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_TransUnet.json -tag "768 decoder ch" --cross_val 5 --arch_type "wss" --n_epochs 150 --out 4
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_unet_epi_multi_att_dsv.json -tag "768 decoder ch" --cross_val 5 --arch_type "crag" --n_epochs 150
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_unet_epi_multi_att_dsv.json -tag "768 decoder ch" --cross_val 5 --arch_type "wss" --n_epochs 150 --out 4
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/projects/solo-learn/bash_files/pretrain/imagenet-100/trained_models/nnclr/4/nnclr-400ee-imagenet100-4-ep=59.ckpt -tag "768 decoder ch" --cross_val 5
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/42/selfswin-100ep-medmnist15k-modDepth-42-ep=99.ckpt -tag "768 decoder ch" --cross_val 5
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/46/selfswin-100ep-medmnist290k-modDepth-46-ep=99.ckpt -tag "768 decoder ch" --cross_val 5
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/41/selfswin-100ep-medmnist-modDepth-41-ep=99.ckpt -tag "768 decoder ch" --cross_val 5
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/2/selfswin-10ep-imagenet15k-modDepth-2-ep=99.ckpt -tag "768 decoder ch" --cross_val 5
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/50/selfswin-100ep-medmnist64k-91C-modDepth-50-ep=99.ckpt -tag "768 decoder ch" --cross_val 5
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain  /home/uz1/trained_models/selfswin/58/selfswin-100ep-medmnist91_32k-imagenet_100_32k-modDepth-58-ep=99.ckpt -tag "768 decoder ch" --cross_val 5
python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain  /home/uz1/trained_models/selfswin/64/selfswin-100ep-medmnist91_32k-imagenet_100_32k-modDepth-64-ep=58.ckpt -tag "768 decoder ch" --cross_val 5 --arch_type "crag" --n_epochs 150
python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain  /home/uz1/trained_models/selfswin/64/selfswin-100ep-medmnist91_32k-imagenet_100_32k-modDepth-64-ep=58.ckpt -tag "768 decoder ch" --cross_val 5 --arch_type "crag" --n_epochs 150
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/22/selfswin-60ep-wss-22-ep=59.ckpt -tag "768 decoder ch" --cross_val 5
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/26/selfswin-60ep-peso-modDepth-26-ep=59.ckpt -tag "768 decoder ch" --cross_val 5
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/28/selfswin-200ep-peso-modDepth-28-ep=199.ckpt -tag "768 decoder ch" --cross_val 5 --arch_type "glas" --n_epochs 60
# python /home/uz1/projects/codeServerEPI/pywich_test.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup.json -cont True -pretrain /home/uz1/trained_models/selfswin/50/selfswin-100ep-medmnist64k-91C-modDepth-50-ep=99.ckpt -tag "768 decoder ch" --cross_val 5 --arch_type "crag" --n_epochs 150
# python /home/uz1/projects/codeServerEPI/train_classifaction.py -c /home/uz1/projects/codeServerEPI/configs/config_SwinT_v2_decoderCup_class.json -cont True -pretrain /home/uz1/trained_models/simclr/86/simclr-20ep-svs-86-ep=18.ckpt -tag "768 decoder ch" --cross_val 5 --arch_type "wss_class"
